title: Study
email: loststar0504@gmail.com
description: For study
github_username: loststar0504
minimal_mistakes_skin: default
search: true

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

author:
  name   : "Hwisang Jeon"
  bio    : "."

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
